# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_song_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_logo',
        ),
    ]
