# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_song_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='artist_name',
            new_name='genre_name',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
    ]
