# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170501_0251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Artist',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='genre_name',
            new_name='artist_name',
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
