# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20170501_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_pic',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
