# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_artist_artist_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
