# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20170503_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
