# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20170505_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_file',
        ),
    ]
