# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_song_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default='static/music/images/background.jpg', upload_to=''),
        ),
    ]
