# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20170505_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
